version: "3.9"

services:
  node_app:
    container_name: node_app
    build: .
    image: francescoxx/node_live_app
    ports:
      - "3000:3000"
    environment:
      - DB_HOST_LOCAL=node_db
      - DB_PORT_LOCAL=5432
      - DB_DATABASE=node_live_db
      - DB_USER=sgcproject
      - DB_PASSWORD=12345
      - SECRET=SOU BOM MEU PATRAO
    depends_on:
      - node_db

  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=node_live_db
      - POSTGRES_USER=sgcproject
      - POSTGRES_PASSWORD=12345
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: {}
